### ISSUE TITLE
Cost model calculation is O(n) rather than O(1)

### ISSUE THREAD

**Issue by butlermh** [snowplow-archive/snowplow-tco-model#3]
The time to calculate the cost increases with the number of events:

```
system.time(costModelNow <- snowplowCostByMonth(1000000, 10000000, 1, 'redshift', 12, 10000))
   user  system elapsed 
  7.932   0.000   7.763 
system.time(costModelFuture <- snowplowCostByMonth(10000000, 100000000, 1, 'redshift', 12, 10000))
   user  system elapsed 
 61.708   0.000  60.504 
```

This is a pain because there is potentially a barrier of entry to using the cost model (installing / using R). 

However it would be fairly easy (1 - 2 hours) to put a [Shiny front end](http://shiny.rstudio.com/) on the cost model and [host it on the web](https://www.shinyapps.io/) to make it interactive. But if the cost model takes a long time to run, that won't work.

Clearly there is a loop somewhere, I need to dig into the code to find it. 

Incidentally another nice tool here is [Knitr](https://github.com/yihui/knitr) - literate programming in R embedded in markdown - you could use this to automate generating the README because it will run R / regenerate the plots.

Coursera introduce [Shiny](https://www.coursera.org/course/devdataprod) and [Knitr](https://www.coursera.org/course/repdata) on their [Data Science Specialization](https://www.coursera.org/specialization/jhudatascience/1?utm_medium=courseDescripLabel).

**Comment by butlermh** [comment]
https://github.com/snowplow/snowplow-tco-model/blob/master/R/s3-cf-log-costs.r#L21

https://github.com/snowplow/snowplow-tco-model/blob/master/R/s3-costs.r#L10

**Comment by butlermh** [comment]
http://stackoverflow.com/questions/22235809/append-value-to-empty-vector-in-r

**Comment by butlermh** [comment]
I see what the problem is - it's the sample function here:

https://github.com/snowplow/snowplow-tco-model/blob/master/R/s3-cf-log-costs.r#L35

That will get increase in expense with eventsPerHour

**Comment by butlermh** [comment]
Intuitively (I don't have a proof) it saturates

if eventsPerHour is > 5 \* edgeLocations then numbOfCfLogsPerHour = edgeLocations

beyond that the calculation gets more expensive but it's easy to guess the answer. I would prefer to see a piece of math that proved this - I guess we have a random discrete uniform sampling distribution - but that didn't help me locate a piece of math that proves that.

**Comment by yalisassoon** [comment]
Hi Mark,

I think you're absolutely right.
Fortunately, if we switch the model to work with the Clojure collector, we
no longer have to worry about computing all the Cloudfront edge locations.
(This was necessary to compute how many S3 log files files would be
generated, which is a big driver of S3 costs when you're using the
Cloudfront collector, because the large number means lots of HTTP requests
are required for processing them.
Looking forward to diving into all your PRs - many thanks!

Yali

On Thu, Oct 16, 2014 at 1:39 PM, Mark H. Butler notifications@github.com
wrote:

> Intuitively (I don't have a proof) it saturates
> 
> if eventsPerHour is > 5 \* edgeLocations then numbOfCfLogsPerHour =
> edgeLocations
> 
> beyond that the calculation gets more expensive but it's easy to guess the
> answer. I would prefer to see a piece of math that proved this - I guess we
> have a random discrete uniform sampling distribution - but that didn't help
> me locate a piece of math that proves that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/snowplow/snowplow-tco-model/issues/3#issuecomment-59354641
> .

## 

Co-founder
Snowplow Analytics http://snowplowanalytics.com/
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon https://twitter.com/yalisassoon
https://twitter.com/yalisassoon
